### PR TITLE
Add syntax highlighting to READMEs

### PR DESCRIPTION
**Pull request by lucperkins**
IMHO this improves the readability of the READMEs substantially

### CODE REVIEW

**Comment by kebasyaty** [comment]
Hi
Thank you for showing interest in the project.
During the pull request, two errors were discovered, which I corrected. Please update your branches in the fork.

**Comment by lucperkins** [comment]
@kebasyaty Done

**Comment by lucperkins** [comment]
@kebasyaty It looks like someone introduced formatting errors in the Rust code, which is unrelated to these changes.

**Comment by kebasyaty** [comment]
This formatting is fine for VSCode, but not for GitHub.
When I figure it out, I'll let you know.

**Comment by lucperkins** [comment]
This has created a merge conflict and I don't really know the codebase well enough to sort that out, so I'll close this. I would, however, recommend providing syntax highlighting.

**Comment by kebasyaty** [comment]
I checked out the entire project with `cargo fmt --all -- --check` and updated the master branch. The formatting problem was only in the migration.rs file. I think you need to update this file in your fork and resubmit the pull request.

**Pull request merged**
